### ISSUE TITLE
Polar cap

### ISSUE THREAD

**Issue by eatdust** [chris-blues/Nasa2FGearthview#5]
Hi Chris,
because I am doing exhaustive testing on various things, I've spotted something hard to deal with, I am just opening an issue to have it in mind.

The C1/D1 gray bands we are removing are actually not artefacts but the polar cap which ends up being dislocated over all the northern maps due to the projection.

I have spotted it because if you look carefully into the input/world_*_A1 map, top left border, it is there actually as well. And it ends up in the world_N1.png map as well thereby creating a quarter of a polar cap in Earthview at the end.

It is quite difficult to deal with that, because the process of extending some pixels to the edges for C1 and D1 are actually killing parts of the polar cap. So we could either remove that, improve it, or also, we could make a big border on A1 to get Earth without any polar cap at all. Somehow, this will be accurate in a few decades from now on (dramatically!)

**Comment by chris-blues** [comment]
That explains it alright! This was always an annoyance to me, that there was no good (hi-res) polar ice cap data available. I kept thinking about it on and off since this all started. Doing the tests last week, I found that texture ice_land_snow (or sth like this). That might provide a nice ice cap. But I haven't come around looking into it...

As I recall, this might be a pretty small thing to do, to grab all the white parts and put it on earth*.png. Just a thought, maybe it's rubbish. Idk...

**Comment by chris-blues** [comment]
This is, what data is there on the nightlights texture in original. I cropped a small piece out of the dnb_land_ocean_ice.blah-geo.tif and cranked up the exposure time in GIMP. Not pretty, but maybe enough, considering, that in the polar regions we already have a lot of distortion due to the nature of scaling a rectangular texture on a sphere...

This is the NASA original viewed at 100%:
![Bildschirmfoto von 2020-02-06 17-42-30](https://user-images.githubusercontent.com/15331023/73958751-abda5500-4908-11ea-8155-dba58a1b9ce2.png)

Now I suspect, there is a certain color value indicating ice. I'll try to see what I get if I go for filtering out anything else. Maybe we'll have a good-enough polar cap to disguise all the problematic data...

**Comment by eatdust** [comment]
Hey, we could also fake one. When you crop that pixel and make the bluebar.mpc, we could instead make something else, like a distorted bluestrip with the right color. Maybe the rendering would be acceptable once projected?

**Comment by chris-blues** [comment]
As I remember, the blue_bar spreads over 2 or 3 tiles. But only the uppermost few lines, which means it ends up as a tiny round circle around the nothern pole. I'd gess with a radius of a few kilometers. Hardly visible from orbit.

Remember, the uppermost line of pixels is projected as a dot on top of the pole. A 32kP dot!

**Comment by eatdust** [comment]
Yes, right, although it is quite big, its size is resolution_max/14, sort of 1700 pixels (that's why I was seeing it). And indeed, the residual polar cap lines on N1 extends quite low (that is the one not corrected).
I am having a look to this, amazing:
https://www.imagemagick.org/Usage/distorts/#polar

We just need a good polar picture and use that instead of the bluebar.mpc!

**Comment by chris-blues** [comment]
Been there... :(

The maps at NASA don't match the available projections for imageMagick...

Edit: gotta go now. CYa tomorrow...

**Comment by eatdust** [comment]
I've just pushed some changes, added a bluebar cleaning on world_N1 (A1 NASA) to be completely free of any polar cap residuals. That does not fix that we miss the pole, but at least, nothing remains now. I am closing.
